Include the esp_vfs_fat.h header
esp-rs/esp-idf-sys pull request #56
Opened 2022-01-15 23:40 UTC by derchr

I needed to use the FatFs driver and want to share my modifications.

2022-01-28 21:28 UTC, ivmarkov requested changes

2022-01-28 21:28 UTC, ivmarkov commented on src/include/esp-idf/bindings.h
>  #ifdef ESP_IDF_COMP_APP_UPDATE_ENABLED
I don't think a component named "esp_vfs_fat" exists? Usually, the components are named after their corresponding names in the `components/` folder of ESP-IDF (modulo replacing - with _). I don't see `esp_vfs_fat` there. What _is_ there, is `fatfs`.

2022-01-29 06:39 UTC, ivmarkov commented
I'll merge and then fix myself.

2022-01-29 06:54 UTC, ivmarkov commented
Accommodated here: https://github.com/esp-rs/esp-idf-sys/commit/1d9adac0aa916dcdfda64fd48084aa3ed024e6bc

2022-01-29 06:54 UTC, closed without merging

2022-02-01 19:32 UTC, derchr commented
Thanks for adding this.
What I noticed is that somehow the first 3 bytes of all files that are being read from the filesystem get truncated. I'm pretty sure this wasn't happening last week as I've successfully loaded some images from the fs.
Also, using my version of the pull request does not resolve this either, so the changes in esp-idf-sys are most likely not the problem here.

This all seems very weird. Is there maybe another moving part that could have caused this?

2022-02-02 06:55 UTC, ivmarkov commented
Without a simple repro case it is difficult to say what is going on